### ISSUE TITLE
redux-persist

### ISSUE THREAD

**Issue by webcrg** [Fing0r/Weather_React#2]
https://github.com/Fing0r/Weather_React/blob/56cd5d8ec0242b413113c1d208de1cf11db5b0b3/src/pages/weather/component/favorite-cities/favorite-cities.tsx#L13-L15

можно использовать для работы с хранилищем redux-persist, достаточно удобная штука
но для него нужно будет дописать некоторые правила в configureStore, иначе будет сыпать ошибками
https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist

**Comment by Fing0r** [comment]
спасибо!
